#local profile
server:
  address : 0.0.0.0
  port : 8080
  servlet:
    context-path: /api
spring:
  config:
    activate:
      on-profile: local
  
  application:
    name: moun
  
  datasource:
    url: jdbc:mysql://localhost:3306/moun
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update #change to none after create once
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: false
  
  #sql:
    #init:
      #mode:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true


---
# test profile
spring:
  config:
    activate:
      on-profile: test


  datasource:
    url: jdbc:mysql://172.26.0.10:3306/moun
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
#  sql:
#    init:
#      mode: never

--- #upload test

spring:
  servlet:
    multipart:
      enabled: true
      location: ${LOCAL_UPLOAD_DIR}
      max-request-size: 25MB
      max-file-size: 20MB
---