services:
  web:
#    build: .
    image: test8
#    depends_on:
#      - db
    ports:
      - "8080:8080"
    environment:
    - MYSQL_PASSWORD=password
    - SPRING_ACITVE_PROFILES=test
#  db:
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#    ports:
#      - "3306:3306"
