services:
  db:
    image: mysql

    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moun
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    networks:
      default_bridge:
        ipv4_address: 172.26.0.10
  web:
#    build: .
    image: test10
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
    - LOCAL_UPLOAD_DIR=/upload
    - MYSQL_PASSWORD=password
    - SPRING_ACTIVE_PROFILES=test
    networks:
      default_bridge:
        ipv4_address: 172.26.0.13


networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16